development:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  database: <%= ENV['MYSQL_DB'] || 'testapp_mysql2_development' %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  <%= ENV['MYSQL_HOST'] ? 'host: ' + ENV['MYSQL_HOST'] : 'socket: /tmp/mysql.sock' %>
  
test:
  adapter: mysql2
  encoding: utf8
  collation: utf8_general_ci
  database: <%= ENV['MYSQL_DB'] || 'testapp_mysql2_test' %>
  username: <%= ENV['MYSQL_USER'] || 'root' %>
  password: <%= ENV['MYSQL_PASSWORD'] || '' %>
  <%= ENV['MYSQL_HOST'] ? 'host: ' + ENV['MYSQL_HOST'] : 'socket: /tmp/mysql.sock' %>
